
#Authors: sheida samadi , baran farrokhian , parsa bastami



#getting txt file 
txt ="""Unveiling the Magic: A Dive into Software Engineering 
Software engineering is the fascinating discipline that transforms intangible ideas into the digital tools and applications that shape our world. It's the bridge between the creativity of computer science and the rigor of engineering. Software engineers are the architects of the digital age, wielding code as their building blocks to construct intricate systems that power everything from our smartphones to self-driving cars.
At its core, software engineering revolves around the systematic development of software. This isn't just about writing lines of code; it's a meticulous process that involves several well-defined stages:
Requirement Gathering: The journey begins by understanding the problem or need that the software is meant to address. This involves gathering requirements from stakeholders, which could be users, businesses, or other developers.
Design and Architecture: Once the requirements are clear, software engineers design the software's architecture, defining its overall structure and how its various components will interact. This blueprint ensures the software is scalable, maintainable, and meets the performance goals.
Implementation: With a solid plan in place, the coding magic happens. Software engineers translate the design into actual code, using specific programming languages and tools best suited for the task.
Testing and Debugging: No software is perfect, so rigorous testing is essential. Engineers create test cases to uncover bugs and ensure the software functions as intended under various conditions. Debugging involves identifying and fixing these errors to create a polished and reliable product.
Deployment and Maintenance: Once the software is thoroughly tested, it's deployed to the real world, where users can interact with it. Software engineers don't abandon their creations after deployment; they continuously monitor performance, fix bugs that may arise in real-world use, and implement new features based on user feedback.
Software engineering is a vast field with numerous specializations. Some engineers focus on front-end development, crafting the user interfaces that we interact with. Others delve into back-end development, building the complex systems that power the applications behind the scenes. There are also specialists in areas like security, mobile app development, and database management.
The tools and technologies used in software engineering are constantly evolving. Today's engineers leverage powerful frameworks, cloud computing platforms, and cutting-edge programming languages like Python, Java, and JavaScript. The ability to learn and adapt to these advancements is crucial for success in this dynamic field.
But software engineering is more than just code and technology. It's about collaboration, problem-solving, and critical thinking. Software engineers work in teams, exchanging ideas, troubleshooting issues, and striving for a shared goal. They must be able to break down complex challenges into smaller, manageable tasks and devise efficient solutions.
The impact of software engineering is undeniable. It has revolutionized every aspect of our lives, from communication and entertainment to healthcare and scientific discovery. As we hurtle towards a future increasingly reliant on technology, the role of software engineers will only become more prominent.
If you're fascinated by technology and enjoy tackling intricate problems, software engineering could be the perfect path for you. It's a challenging but rewarding career that offers immense opportunities for creativity, innovation, and making a real difference in the world.
This is just a glimpse into the captivating world of software engineering. As you delve deeper, you'll discover a universe of possibilities waiting to be explored by the next generation of digital architects. Are you ready to answer the call?
*this text is generated by Google Bard (2024)."""

# counting letters
a = int(txt.lower().count('a'))
b = int(txt.lower().count('b'))
c = int(txt.lower().count('c'))
d = int(txt.lower().count('d'))
e = int(txt.lower().count('e'))
f = int(txt.lower().count('f'))
g = int(txt.lower().count('g'))
h = int(txt.lower().count('h'))
i = int(txt.lower().count('i'))
j = int(txt.lower().count('j'))
k = int(txt.lower().count('k'))
l = int(txt.lower().count('l'))
m = int(txt.lower().count('m'))
n = int(txt.lower().count('n'))
o = int(txt.lower().count('o'))
p = int(txt.lower().count('p'))
q = int(txt.lower().count('q'))
r = int(txt.lower().count('r'))
s = int(txt.lower().count('s'))
t = int(txt.lower().count('t'))
u = int(txt.lower().count('u'))
v = int(txt.lower().count('v'))
w = int(txt.lower().count('w'))
x = int(txt.lower().count('x'))
y = int(txt.lower().count('y'))
z = int(txt.lower().count('z'))
letters =[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z]
All_letters =(a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z)

def count_leetter ():
    print('Number Of Letters :')
    print('a :' , a)
    print('b :' , b)
    print('c :' , c)
    print('d :' , d)
    print('e :' , e)
    print('f :' , f)
    print('g :' , g)
    print('h :' , h)
    print('i :' , i)
    print('j :' , j)
    print('k :' , k)
    print('l :' , l)
    print('m :' , m)
    print('n :' , n)
    print('o :' , o)
    print('p :' , p)
    print('q :' , q)
    print('r :' , r)
    print('s :' , s)
    print('t :' , t)
    print('u :' , u)
    print('v :' , v)
    print('w :' , w)
    print('x :' , x)
    print('y :' , y)
    print('z :' , z)





count_leetter();    

# counting words
print('Number Of Words : ', len(txt.split()))


#counting sentences 
print('Number Of Srntences : ' ,len(txt.split('.')))

#counting paraghraph
print('Number Of Paragraphs :' , len(txt.split('\n')))

# counting vowels letters 
vowels = (a + i + u + e + o)
print('Number Of Vowels :' , vowels )

# counting constant letters
print('Number Of Constant :' , (All_letters-vowels))

# counting average and the variance of the letters in all the text
print(All_letters)
average  = (All_letters/len(letters))
print('Average In All The Text File Is :', average)
import statistics
vari = statistics.variance(letters)
print ('Vaiance In All The Text File Is :',vari)